name = "study-with-miku"
compatibility_date = "2023-10-01"

[site]
bucket = "./dist"
entry-point = "."

[env.production]

[[routes]]
pattern = "https://study.mikugame.icu/*"
custom_domain = true

[[routes]]
pattern = "https://study.mikumod.com/*"
custom_domain = true
